[default_view]

keymap = [
	{ keys = [ "escape" ],		command = "escape" },

	{ keys = [ "q" ],		command = "close_tab" },
	{ keys = [ "Q" ],		command = "quit" },

	{ keys = [ "R" ],		command = "reload_dirlist" },

	{ keys = [ "t", "t" ],		command = "new_tab --current" },
	{ keys = [ "t", "l" ],		command = "tab_switch 1" },
	{ keys = [ "t", "h" ],		command = "tab_switch -1" },
	{ keys = [ "ctrl+l" ],		command = "tab_switch 1" },
	{ keys = [ "ctrl+h" ],		command = "tab_switch -1" },
	{ keys = [ "t", "1" ],		command = "tab_switch_index 1" },
	{ keys = [ "t", "2" ],		command = "tab_switch_index 2" },
	{ keys = [ "t", "3" ],		command = "tab_switch_index 3" },
	{ keys = [ "t", "4" ],		command = "tab_switch_index 4" },
	{ keys = [ "t", "5" ],		command = "tab_switch_index 5" },
	{ keys = [ "t", "6" ],		command = "tab_switch_index 6" },
	{ keys = [ "t", "7" ],		command = "tab_switch_index 7" },
	{ keys = [ "t", "8" ],		command = "tab_switch_index 8" },
	{ keys = [ "t", "9" ],		command = "tab_switch_index 9" },

	{ keys = [ "1" ],		command = "numbered_command 1" },
	{ keys = [ "2" ],		command = "numbered_command 2" },
	{ keys = [ "3" ],		command = "numbered_command 3" },
	{ keys = [ "4" ],		command = "numbered_command 4" },
	{ keys = [ "5" ],		command = "numbered_command 5" },
	{ keys = [ "6" ],		command = "numbered_command 6" },
	{ keys = [ "7" ],		command = "numbered_command 7" },
	{ keys = [ "8" ],		command = "numbered_command 8" },
	{ keys = [ "9" ],		command = "numbered_command 9" },

	# arrow keys
	{ keys = [ "\n" ],		command = "open" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "end" ],		command = "cursor_move_end" },
	{ keys = [ "page_up" ],		command = "cursor_move_page_up" },
	{ keys = [ "page_down" ],	command = "cursor_move_page_down" },

	# vim-like keybindings
	{ keys = [ "j" ],		command = "cursor_move_down" },
	{ keys = [ "k" ],		command = "cursor_move_up" },
	{ keys = [ "J" ],		command = "cursor_move_down 5" },
	{ keys = [ "K" ],		command = "cursor_move_up 5" },
	{ keys = [ "h" ],		command = "cd .." },
	{ keys = [ "l" ],		command = "open" },
	{ keys = [ "g", "g" ],		command = "cursor_move_home" },
	{ keys = [ "G" ],		command = "cursor_move_end" },
	{ keys = [ "r" ],		command = "open_with" },

	{ keys = [ "c", "d" ],		command = ":cd " },

	{ keys = [ "delete" ],		command = "delete_files" },
	{ keys = [ "d", "D" ],		command = "delete_files" },
	{ keys = [ "d", "d" ],		command = "cut_files" },

	{ keys = [ "y", "y" ],		command = "copy_files" },
	{ keys = [ "y", "n" ],		command = "copy_filename" },
	{ keys = [ "y", "." ],		command = "copy_filename_without_extension" },
	{ keys = [ "y", "p" ],		command = "copy_filepath" },
	{ keys = [ "y", "d" ],		command = "copy_dirpath" },
	{ keys = [ "y", "l" ],		command = "symlink_files --relative=false" },
	{ keys = [ "y", "L" ],		command = "symlink_files --relative=true" },

	{ keys = [ "p", "p" ],		command = "paste_files" },
	{ keys = [ "p", "o" ],		command = "paste_files --overwrite=true" },

	{ keys = [ " " ],			command = "select --toggle=true" },
	{ keys = [ "V" ],			command = "toggle_visual"},
	{ keys = [ "v", "v" ],		command = "select --all=true --toggle=true" },
	{ keys = [ "v", "x" ],		command = "select --all=true --deselect=true"},

	{ keys = [ "z", "h" ],		command = "toggle_hidden" },

	{ keys = [ "c", "m" ],		command = "set_mode" },
	{ keys = [ "c", "n" ],		command = ":rename " },
	{ keys = [ "c", "a" ],		command = "rename_append_base" },
	{ keys = [ "c", "A" ],		command = "rename_append" },
	{ keys = [ "c", "p" ],		command = "rename_prepend" },
	{ keys = [ "c", "w" ],		command = "rename_keep_ext" },
	{ keys = [ "c", "b" ],		command = "bulk_rename" },

	{ keys = [ ":" ],		command = ":" },
	{ keys = [ ";" ],		command = ":" },

	{ keys = [ "'" ],		command = ":shell " },
	{ keys = [ "S" ],		command = "shell zsh" },
	{ keys = [ "T" ],		command = ":touch " },
	{ keys = [ "M" ],		command = ":mkdir " },

	{ keys = [ "ctrl+v" ],		command = "shell nvim" },
	{ keys = [ "ctrl+g" ],		command = "shell lazygit" },

	# TODO
	# { keys = [ "z", "p" ],		command = ":shell /Users/nofoot/.config/joshuto/zip %p " },
	# { keys = [ "z", "u" ],		command = ":shell /Users/nofoot/.config/joshuto/zip %p " },

	{ keys = [ "/" ],		command = ":search_inc " },
	{ keys = [ "?" ],		command = ":filter  " },
	{ keys = [ "\\" ],		command = ":search_glob " },
	{ keys = [ "ctrl+f" ],		command = "subdir_fzf" },

	{ keys = [ "n" ],		command = "search_next" },
	{ keys = [ "N" ],		command = "search_prev" },

	{ keys = [ "s", "r" ],		command = "sort reverse" },
	{ keys = [ "s", "l" ],		command = "sort lexical" },
	{ keys = [ "s", "t" ],		command = "sort mtime" },
	{ keys = [ "s", "n" ],		command = "sort natural" },
	{ keys = [ "s", "s" ],		command = "sort size" },
	{ keys = [ "s", "e" ],		command = "sort ext" },

	{ keys = [ "i", "s" ],		command = "linemode size" },
	{ keys = [ "i", "t" ],		command = "linemode mtime" },

	{ keys = [ "g", "r" ],		command = "cd /" },
	{ keys = [ "g", "d" ],		command = "cd ~/Downloads" },
	{ keys = [ "g", "D" ],		command = "cd ~/Desktop" },
	{ keys = [ "g", "h" ],		command = "cd ~/" },
	{ keys = [ "g", "c" ],		command = "cd ~/.config" },
	{ keys = [ "g", "p" ],		command = "cd -" },
		
	{ keys = [ "w" ],		command = "show_tasks --exit-key=w" },
]

[task_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],	command = "cursor_move_down" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "end" ],		command = "cursor_move_end" },

	# vim-like keybindings
	{ keys = [ "j" ],		command = "cursor_move_down" },
	{ keys = [ "k" ],		command = "cursor_move_up" },
	{ keys = [ "g", "g" ],		command = "cursor_move_home" },
	{ keys = [ "G" ],		command = "cursor_move_end" },

	{ keys = [ "w" ],		command = "show_tasks" },
	{ keys = [ "escape" ],		command = "show_tasks" },
]

[help_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],	command = "cursor_move_down" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "end" ],		command = "cursor_move_end" },

	# vim-like keybindings
	{ keys = [ "j" ],		command = "cursor_move_down" },
	{ keys = [ "k" ],		command = "cursor_move_up" },
	{ keys = [ "J" ],		command = "cursor_move_down 5" },
	{ keys = [ "K" ],		command = "cursor_move_up 5" },
	{ keys = [ "g", "g" ],		command = "cursor_move_home" },
	{ keys = [ "G" ],		command = "cursor_move_end" },

	{ keys = [ "w" ],		command = "show_tasks" },
	{ keys = [ "escape" ],		command = "show_tasks" },
	{ keys = [ "q" ],		command = "show_tasks" },
]
